// Generated by CoffeeScript 1.10.0
(function() {
  var csv, csvStream, fs, list, populateArray, readFile, stream;

  csv = require('fast-csv');

  fs = require('fs');

  list = [];

  stream = fs.createReadStream("C:/Users/Kozitski/Downloads/9d3dfb739fc3-list+of+urls.csv");

  csvStream = csv().on('data', function(data) {
    list.push(data);
    populateArray(data);
  }).on('end', function() {});

  stream.pipe(csvStream);

  readFile = function() {
    console.log(list);
  };

  populateArray = function(temp) {
    list.push(temp);
  };

}).call(this);
