// Generated by CoffeeScript 1.10.0
(function() {
  var cheerio, csv, csvStream, fs, list, readFile, request, stream;

  csv = require('fast-csv');

  fs = require('fs');

  cheerio = require('cheerio');

  request = require('request');

  list = [];

  stream = fs.createReadStream("C:/Users/ekozi/Downloads/9d3dfb739fc3-list+of+urls.csv");

  csvStream = csv().on('data', function(data, err) {
    if (err) {
      throw err;
    } else {
      list.push(data);
    }
  }).on('end', function() {
    readFile(list);
  });

  stream.pipe(csvStream);

  readFile = function(list) {
    return list.forEach(function(data) {
      return request(data[0], function(err, response, html) {
        var $;
        if (err) {
          return console.log(data[0]);
        } else {
          $ = cheerio.load(html);
          return console.log(this);
        }
      });
    });
  };

}).call(this);
